"""initial schema

Revision ID: c088b170994b
Revises: 
Create Date: 2026-08-24 14:16:52.889576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c088b170994b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('payment_history_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_in_paise', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('error_source', sa.String(length=100), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('amount_at_risk', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_PROGRESS', 'RECOVERED', 'ESCALATED', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('failure_category', sa.Enum('INSUFFICIENT_FUNDS', 'CARD_DECLINED', 'EXPIRED_CARD', 'GATEWAY_TIMEOUT', 'TECHNICAL_FAILURE', 'AUTHENTICATION_FAILED', name='failurecategory'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('recovery_probability', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('selected_strategy', sa.Enum('IMMEDIATE_RETRY', 'RETRY_AFTER_DELAY', 'SEND_PAYMENT_LINK', 'SEND_EMAIL_REMINDER', 'SEND_SMS_REMINDER', 'SEND_WHATSAPP_MESSAGE', 'OFFER_ALT_PAYMENT_METHOD', 'HUMAN_ESCALATION', 'STOP_RECOVERY', name='strategytype'), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.Enum('AI_AGENT', 'SYSTEM', 'CUSTOMER', 'HUMAN_OPERATOR', 'SAFETY_ENGINE', name='actortype'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', name='communicationchannel'), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='communicationdirection'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promise_to_pay',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('promised_date', sa.DateTime(), nullable=False),
    sa.Column('promised_amount', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REMINDER_SENT', 'KEPT', 'BROKEN', name='promisestatus'), nullable=False),
    sa.Column('reminder_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('IMMEDIATE_RETRY', 'RETRY_AFTER_DELAY', 'SEND_PAYMENT_LINK', 'SEND_EMAIL_REMINDER', 'SEND_SMS_REMINDER', 'SEND_WHATSAPP_MESSAGE', 'OFFER_ALT_PAYMENT_METHOD', 'HUMAN_ESCALATION', 'STOP_RECOVERY', name='strategytype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'EXECUTED', 'FAILED', 'BLOCKED', name='actionstatus'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('original_amount', sa.Integer(), nullable=False),
    sa.Column('recovered_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_RECOVERED', 'FULLY_RECOVERED', 'NOT_RECOVERED', name='recoveryresultstatus'), nullable=False),
    sa.Column('recovery_method', sa.String(length=100), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('recovery_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.Enum('IMMEDIATE_RETRY', 'RETRY_AFTER_DELAY', 'SEND_PAYMENT_LINK', 'SEND_EMAIL_REMINDER', 'SEND_SMS_REMINDER', 'SEND_WHATSAPP_MESSAGE', 'OFFER_ALT_PAYMENT_METHOD', 'HUMAN_ESCALATION', 'STOP_RECOVERY', name='strategytype'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('expected_probability', sa.Integer(), nullable=True),
    sa.Column('stopping_rules', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('communication_id', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.Enum('POSITIVE_PAYMENT_INTENT', 'PROMISE_TO_PAY', 'PAYMENT_PROBLEM', 'ALT_METHOD_REQUESTED', 'REFUSAL', 'NO_RESPONSE', name='intenttype'), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_responses')
    op.drop_table('recovery_strategies')
    op.drop_table('recovery_results')
    op.drop_table('recovery_actions')
    op.drop_table('promise_to_pay')
    op.drop_table('communications')
    op.drop_table('audit_logs')
    op.drop_table('recovery_cases')
    op.drop_table('payment_attempts')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
